### ISSUE TITLE
Stopping bug using the vscode debug adapter

### ISSUE THREAD

**Issue by gabfv** [robot256/rocket-log#3]
Hi,
When loading a save that has rocket log enabled and using the vscode debug adapter to debug something, 
The following error shows up:
__rocket-log__/control.lua:58: 
[ER Global Lock] Forbidden global *read*:
{key = "game"}
__rocket-log__/control.lua:58: 
[ER Global Lock] Forbidden global *read*:
{key = "game"}

Of course, removing the mod fixes the issues but I was wondering if there's another way to find local variables used globally?

**Comment by robot256** [comment]
The check is to make sure you don't accidentally create a global variable that is not stored within the "global" API table.  You can disable this check by commenting out the "setmetatable..." block in control.lua.  It sounds like the vscode adapter runs the Lua outside the normal game context, so the Factorio API object "game" either doesn't exist or is treated as a different type of variable than the normal Factorio Lua API.

**Comment by Quezler** [comment]
i'll have to remove this mod from my se playthrough because it doesn't play nice with the vscode debug adapter too.

**Comment by robot256** [comment]
Thanks for commenting.  I realized this was caused by code that is only required for debugging, so I commented it out and released a new version.  This should be resolved now.
